### ISSUE TITLE
no me agregaron qlones

### ISSUE THREAD

**Issue by abrahamhurtado** [gaverdugo/react-chat#1]

**Comment by Nifled** [comment]
Perdon, no noobs.... Este repo... es para profesionales... 🙃

**Comment by gaverdugo** [comment]
<img width="788" alt="captura de pantalla 2018-02-17 a la s 10 02 22" src="https://user-images.githubusercontent.com/7308497/36343464-e2b5b89c-13c9-11e8-8241-909aba9d7606.png">
Desde hace un chorro que te agregue, no has aceptado.
